version : 2.1

jobs:
  say_hello:
    docker:
      - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"

  say_goodbye:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say goodbye to YAML!"


workflows:
  hello_and_goodbye:
    jobs:
      - say_hello
      - say_goodbye
